apiVersion: v1
kind: Secret
metadata:  
  name: '{{ .Release.Name }}-worker-secret'
  namespace: {{ .Values.worker.namespace | default "default" }}
type: Opaque
data:  
  {{- range $key, $value := .Values.worker.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

