FROM node:20-alpine AS build

WORKDIR /usr/src/monorepo

COPY package*.json ./
COPY . .

RUN npm install

RUN npx nx reset

RUN npx nx build api

FROM node:20-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/monorepo

COPY package*.json ./
COPY db-ssl-certificate.crt ./

RUN npm install --omit=dev

COPY --from=build /usr/src/monorepo/dist ./dist

CMD [ "node", "dist/apps/api/main" ]

