FROM node:20-alpine AS build

WORKDIR /app

# Copy Everything from root to workdir
COPY . .

RUN npm install -g pnpm

RUN pnpm install

RUN npx nx reset

RUN npx nx build api

FROM node:20-alpine AS production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /app

COPY package*.json ./
COPY db-ca.crt ./

RUN npm install -g pnpm

RUN pnpm install --omit=dev

COPY --from=build /app/dist ./dist

CMD [ "node", "dist/apps/api/main" ]

