{{- range .Values.workers.languages }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ $.Release.Name }}-worker-{{ .name }}'
  namespace: {{ .namespace | default "default" }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: '{{ $.Release.Name }}-worker-{{ .name }}'
  template:
    metadata:
      labels:
        app: '{{ $.Release.Name }}-worker-{{ .name }}'
    spec:
      containers:
        - name: worker
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.imagePullPolicy}}
          envFrom:
            - configMapRef:
                name: '{{ $.Release.Name }}-worker-{{ .name }}-config'
            - secretRef:
                name: '{{ $.Release.Name }}-worker-secret'
          resources:
            limits:
              cpu: {{ .resources.limits.cpu}}
              memory: {{ .resources.limits.memory}}
            requests:
              cpu: {{ .resources.requests.cpu}}
              memory: {{ .resources.requests.memory}}         
{{- end }}