{{- range .Values.workers.languages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ $.Release.Name }}-worker-{{ .name }}-config'
  namespace: {{ .namespace | default "default" }}
data:
  {{- range $key, $value := .configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
