apiVersion: v1
kind: Secret
metadata:
  name: api-tls
  namespace: {{ .Values.api.namespace | default "default"}}
data:
  tls.crt: {{ .Values.api.tls.crt }}
  tls.key: {{ .Values.api.tls.key }}
type: kubernetes.io/tls