apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-client-config'
  namespace: {{ .Values.client.namespace | default "default" }}
data:
  {{- range $key, $value := .Values.client.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
