apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-client'
  labels:
    app: '{{ .Release.Name }}-client'
  namespace: {{ .Values.client.namespace | default "default" }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Release.Name }}-client'
  template:
    metadata:
      labels:
        app: '{{ .Release.Name }}-client'
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.imagePullPolicy}}
          ports:
            - containerPort: 4200
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-client-config'
          resources:
            limits:
              cpu: {{ .Values.client.resources.limits.cpu}}
              memory: {{ .Values.client.resources.limits.memory}}
            requests:
              cpu: {{ .Values.client.resources.requests.cpu}}
              memory: {{ .Values.client.resources.requests.memory}}