apiVersion: v1
kind: Secret
metadata:
  name: client-tls
  namespace: {{ .Values.client.namespace | default "default"}}
data:
  tls.crt: {{ .Values.client.tls.crt | quote }}
  tls.key: {{ .Values.client.tls.key | quote }}
type: kubernetes.io/tls