apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-server'
  namespace: {{ .Values.server.namespace | default "default" }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app: '{{ .Release.Name }}-server'
  template:
    metadata:
      labels:
        app: '{{ .Release.Name }}-server'
    spec:
      containers:
        - name: server
          image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
          ports:
            - containerPort: 3333
          envFrom:
            - configMapRef:
                name: '{{ .Release.Name }}-server-config'
            - secretRef:
                name: '{{ .Release.Name }}-server-secret'
          resources:
            limits:
              cpu: {{ .Values.server.resources.limits.cpu}}
              memory: {{ .Values.server.resources.limits.memory}}
            requests:
              cpu: {{ .Values.server.resources.requests.cpu}}
              memory: {{ .Values.server.resources.requests.memory}}
