apiVersion: v1
kind: Secret
metadata:  
  name: '{{ .Release.Name }}-server-secret'
  namespace: {{ .Values.server.namespace | default "default" }}
type: Opaque
data:  
  {{- range $key, $value := .Values.server.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}