apiVersion: v1
kind: ConfigMap
metadata:  
  name: {{ .Release.Name }}-api-config
data:
  CODE_EXECUTION_REQUEST_URL: "http://{{ .Release.Name }}-server:3333/api/submissions"
  {{- range $key, $value := .Values.api.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
