{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api
  annotations:
    {{- toYaml .Values.api.ingress.annotations | nindent 4 }}
spec:
  rules:
    - host: api.{{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-api
                port: 
                  number: {{ .Values.api.service.port }}
  tls:
    - hosts:
        - api.{{ .Values.global.domain }}
      secretName: api-tls
{{- end }}