apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 3333
  selector:
    app: {{ .Release.Name }}-server
