{{- range .Values.workers.languages }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-worker-{{ .name }}-config
data:
  {{- range $key, $value := .configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
